version: '3.7'
services:
  samba:
    image: thrashplay/samba-armhf:latest
    ports:
      - "139:139/tcp"
      - "445:445/tcp"
    entrypoint: /sbin/tini -- /bin/bash -c "/usr/bin/samba.sh -r $$(< /run/secrets/smb-users)"
    environment:
      - GROUPID=0
      - INCLUDE=/etc/samba/smb-local.conf
      - TZ=America/Chicago
      - USERID=0
      - WORKGROUP=CONCLAVE
    volumes:
      - backup:/mount/backup
      - home:/mount/home
      - shared:/mount/shared
    configs:
      - source: smb-conf
        target: /etc/samba/smb-local.conf
    secrets:
      - smb-users

configs:
  smb-conf:
    name: smb-conf-${SMB_CONF_VERSION:-default}
    file: ./config/smb.conf

secrets:
  smb-users:
    external: true

volumes:
  backup:
    driver: nfs
    name: samba.backup
    driver_opts:
      share: nfs.pegasus:/samba.backup
  home:
    driver: nfs
    name: samba.home
    driver_opts:
      share: nfs.pegasus:/samba.home
  shared:
    driver: nfs
    name: samba.shared
    driver_opts:
      share: nfs.pegasus:/samba.shared