version: '3.7'
services:
  nginx:
    image: thrashplay/nginx-proxy
    environment:
      - DHPARAM_GENERATION=false
    labels:
      - com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - certs:/etc/nginx/certs:ro
      - vhost.d:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html

  letsencrypt-companion:
    image: jrcs/letsencrypt-nginx-proxy-companion:v1.12.1
    environment:
      - DEFAULT_EMAIL=sean@thrashplay.com
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - certs:/etc/nginx/certs:rw
      - vhost.d:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html

  ddns:
    image: thrashplay/ddns-sidecar:latest
    configs:
      - source: ddns-config
        target: /ddns/config.json
        mode: 0440
    environment:
      - CONFIG_SECRETS_FILE=/run/secrets/ddns-secrets
    ports:
      - "8000:8000"
    secrets:
      - ddns-secrets
    volumes:
      - ddns-data:/updater/data

configs:
  ddns-config:
    name: ddns-config-${DDNS_CONFIG_VERSION:-default}
    file: ./config/ddns.json

networks:
  default:
    external: true
    name: webgateway

secrets:
  ddns-secrets:
    external: true

volumes:
  certs:
    driver: nfs
    name: nginx-proxy.certs
    driver_opts:
      share: nfs.pegasus:/nginx-proxy.certs
  ddns-data:
    driver: nfs
    name: nginx-proxy.ddns-data
    driver_opts:
      share: nfs.pegasus:/nginx-proxy.ddns-data
  html:
    driver: nfs
    name: nginx-proxy.html
    driver_opts:
      share: nfs.pegasus:/nginx-proxy.html
  vhost.d:
    driver: nfs
    name: nginx-proxy.vhost.d
    driver_opts:
      share: nfs.pegasus:/nginx-proxy.vhost.d
