version: '3.7'

services:
  trigger:
    image: thrashplay/rclone-trigger
    configs:
      - source: crontab
        target: /etc/supercronic/crontab
      - source: filters.txt
        target: /etc/rclone/filters.txt
      - source: rclone-options.json
        target: /etc/rclone/options.json
    environment:
      - RCLONE_OPTIONS_FILE=/etc/rclone/options.json
    networks:
      - default

  rclone:
    image: thrashplay/rclone-service
    configs:
      - source: rclone.conf
        target: /root/.config/rclone/rclone.conf
    deploy:
      labels:
        - "traefik.enable=true"
        # http -> https configuration
        - "traefik.http.routers.backup-agent-http.entrypoints=web"
        - "traefik.http.routers.backup-agent-http.middlewares=https-redirect@file"
        - "traefik.http.routers.backup-agent-http.rule=Host(`backups.the-pegasus.net`)"
        # handle https
        - "traefik.http.routers.backup-agent.entrypoints=websecure"
        - "traefik.http.routers.backup-agent.middlewares=secure@file"
        - "traefik.http.routers.backup-agent.rule=Host(`backups.the-pegasus.net`)"
        - "traefik.http.routers.backup-agent.tls.certresolver=production"
        - "traefik.http.routers.backup-agent.tls.options=default"
        - "traefik.http.services.backup-agent-service.loadbalancer.server.port=5572"
    environment:
      - HTPASSWD_FILE=/run/secrets/.htpasswd
    networks:
      - webgateway
      - default
    secrets:
      - source: backup-agent.gcs-credentials
        target: backup-agent-credentials.json
      - source: backup-agent.htpasswd
        target: .htpasswd
    volumes:
      - backup:/data

configs:
  crontab:
    name: crontab-${CRONTAB_VERSION:-default}
    file: ./config/crontab
  filters.txt:
    name: filters.text-${FILTERS_TXT_VERSION:-default}
    file: ./config/filters.txt
  rclone.conf:
    name: rclone.conf-${RCLONE_CONF_VERSION:-default}
    file: ./config/rclone.conf
  rclone-options.json:
    name: rclone-options.json-${RCLONE_OPTIONS_JSON_VERSION:-default}
    file: ./config/rclone-options.json

networks:
  default:
    external: true
    name: apptier
  webgateway:
    external: true
    name: webgateway

secrets:
  backup-agent.gcs-credentials:
    external: true
  backup-agent.htpasswd:
    external: true

volumes:
  backup:
    driver: nfs
    name: samba.backup
    driver_opts:
      share: nfs.pegasus:/samba.backup
