kind: pipeline
type: docker
name: build-deploy-tools

platform:
  arch: arm
  os: linux

steps:
  - name: build-deployer
    image: plugins/docker
    settings:
      context: projects/pegasus-ops/deployer
      dockerfile: projects/pegasus-ops/deployer/Dockerfile
      password:
        from_secret: DOCKER_PASSWORD
      repo: thrashplay/sophia-deployer
      tags: latest
      username: thrashplay

trigger:
  changeset:
    includes: [ .drone.yaml, projects/pegasus-ops/deployer/** ]
  branch:
    - master
---

kind: pipeline
type: docker
name: build-npm-packages

steps:
  - name: initialize
    image: alpine/git
    commands:
      - git config --local user.email drone@thrashplay.com
      - git config --local user.name Drone

  - name: bootstrap
    image: node:lts
    commands:
      - yarn install --frozen-lockfile --non-interactive
      - yarn lerna bootstrap

  - name: build
    image: node:lts
    commands:
      - yarn build

  - name: test
    image: node:lts
    commands:
      - yarn test

  - name: bump-versions
    image: node:lts
    commands:
      - sh .ci/amend-commit.sh
      - yarn lerna version --conventional-prerelease --preid next --amend --no-changelog --no-push --yes
      - git tag -a builds/${DRONE_BUILD_NUMBER} -m "Tagging build"
      - sh .ci/push-tags.sh
    when:
      branch:
        - master

  - name: authenticate-to-npm
    image: robertstettner/drone-npm-auth
    settings:
      path: ~
      token:
        from_secret: NPM_PUBLISH_TOKEN
    when:
      branch:
        - master

  - name: publish
    image: node:lts
    commands:
      - yarn lerna publish from-package --no-git-reset --dist-tag next --yes
    when:
      branch:
        - master

trigger:
  changeset:
    includes: [
      '.drone.jsonnet',
      '.drone.yaml',
      '.eslintignore',
      '.eslintrc.js',
      '@types/**',
      'babel.conf.js',
      'build-lib/**',
      'jest.config.js',
      'lerna.json',
      'package.json',
      'patches/**',
      'projects/**',
      'tsconfig.*.json',
      'yarn.lock'
    ]
---

kind: pipeline
type: docker
name: deploy-services

depends_on:
  - build-deploy-tools
  - build-npm-packages

platform:
  arch: arm
  os: linux

steps:
  - name: clone
    image: alpine/git
    commands:
    - git clone ${DRONE_REPO_LINK} .
    - git checkout builds/${DRONE_BUILD_NUMBER}

  - name: calculate-config-versions
    image: node:lts
    commands:
      - npx \@pegasus-ops/config-version-helper services/pegasus/nginx/stack-compose.yaml nginx

  - name: deploy
    image: thrashplay/sophia-deployer
    settings:
      docker_host: control.pegasus:2376
      docker_cacert:
        from_secret: DOCKER_CACERT
      docker_cert:
        from_secret: DOCKER_CERT
      docker_key:
        from_secret: DOCKER_KEY

trigger:
  changeset:
    includes: [ .drone.yaml, projects/pegasus-ops/deployer/**, services/** ]
  branch:
    - master
