kind: pipeline
name: deploy-stacks

steps:
- name: transfer-scripts
  image: appleboy/drone-scp
  when:
    changeset:
      includes: [ .drone.yaml, services/bin/** ]
  settings:
    host:
      from_secret: DEPLOY_HOST
    username:
      from_secret: DEPLOY_USERNAME
    key:
      from_secret: DEPLOY_SSH_KEY
    passphrase:
      from_secret: DEPLOY_KEY_PASSPHRASE
    rm: true
    strip_components: 2
    source:
      - services/bin
    target:
      - /opt/sophia/bin

- name: make-scripts-executable
  image: appleboy/drone-ssh
  when:
    changeset:
      includes: [ .drone.yaml, services/bin/** ]
  settings:
    host:
      from_secret: DEPLOY_HOST
    username:
      from_secret: DEPLOY_USERNAME
    key: 
      from_secret: DEPLOY_SSH_KEY
    passphrase:
      from_secret: DEPLOY_KEY_PASSPHRASE
    script:
      - chmod -R u+x /opt/sophia/bin

- name: transfer-configs
  image: appleboy/drone-scp
  settings:
    host:
      from_secret: DEPLOY_HOST
    username:
      from_secret: DEPLOY_USERNAME
    key: 
      from_secret: DEPLOY_SSH_KEY
    passphrase:
      from_secret: DEPLOY_KEY_PASSPHRASE
    rm: true
    strip_components: 2
    target:
      - /opt/sophia/etc
    source:
      - services/sophia

- name: deploy
  image: appleboy/drone-ssh
  settings:
    host:
      from_secret: DEPLOY_HOST
    username:
      from_secret: DEPLOY_USERNAME
    key: 
      from_secret: DEPLOY_SSH_KEY
    passphrase:
      from_secret: DEPLOY_KEY_PASSPHRASE
    script:
      - cd /opt/sophia/bin
      - ./deploy-stack

when:
  branch:
    - master

trigger:
  changeset:
    includes: [ .drone.yaml, services/** ]
