kind: pipeline
type: docker
name: build-drone-plugins

platform:
  arch: arm
  os: linux

steps:
  - name: docker-edit
    image: plugins/docker
    depends_on: [ clone ]
    settings:
      cache_from: 
        - "thrashplay/docker-edit:master"
        - "thrashplay/docker-edit:${DRONE_BRANCH}"
      context: packages/drone-plugins/docker-edit
      dockerfile: packages/drone-plugins/docker-edit/Dockerfile
      force_tag: true
      password:
        from_secret: DOCKER_PASSWORD
      repo: thrashplay/docker-edit
      tags:
        - latest
        - ${DRONE_BRANCH}
        - ${DRONE_BRANCH}-${DRONE_COMMIT}
      username: thrashplay
    when:
      changeset:
        includes: [ packages/drone-plugins/docker-edit/** ]

  - name: generate-versions
    image: plugins/docker
    depends_on: [ clone ]
    settings:
      context: packages/docker/generate-versions
      dockerfile: packages/docker/generate-versions/Dockerfile
      force_tag: true
      password:
        from_secret: DOCKER_PASSWORD
      repo: thrashplay/generate-versions
      tags:
        - latest
        - ${DRONE_BRANCH}
        - ${DRONE_BRANCH}-${DRONE_COMMIT}
      username: thrashplay
    when:
      changeset:
        includes: [ packages/docker/generate-versions/** ]

  - name: swarm-management
    image: plugins/docker
    depends_on: [ clone ]
    settings:
      context: packages/docker/swarm-management
      dockerfile: packages/docker/swarm-management/Dockerfile
      force_tag: true
      password:
        from_secret: DOCKER_PASSWORD
      repo: thrashplay/swarm-management
      tags:
        - latest
        - ${DRONE_BRANCH}
        - ${DRONE_BRANCH}-${DRONE_COMMIT}
      username: thrashplay
    when:
      changeset:
        includes: [ packages/docker/swarm-management/** ]

  - name: wait-for-service
    image: plugins/docker
    depends_on: [ clone ]
    settings:
      context: packages/drone-plugins/wait-for-service
      dockerfile: packages/drone-plugins/wait-for-service/Dockerfile
      force_tag: true
      password:
        from_secret: DOCKER_PASSWORD
      repo: thrashplay/wait-for-service
      tags:
        - latest
        - ${DRONE_BRANCH}
        - ${DRONE_BRANCH}-${DRONE_COMMIT}
      username: thrashplay
    when:
      changeset:
        includes: [ packages/drone-plugins/wait-for-service/** ]

trigger:
  changeset:
    includes: [ .drone.yaml, packages/docker/**, packages/drone-plugins/** ]
  branch:
    - master

---

kind: pipeline
type: docker
name: build-arm-images

depends_on:
  - build-drone-plugins

platform:
  arch: arm
  os: linux

services:
  - name: docker
    image: docker:19.03.8-dind
    environment:
      DOCKER_TLS_CERTDIR: /certs
    privileged: true
    volumes:
      - name: docker-certs
        path: /certs

steps:
  - name: wait-for-docker
    image: thrashplay/wait-for-service
    depends_on: [ clone ]
    settings:
      host: docker
      port: 2376
      retry_limit: 90

  - name: ddns-sidecar
    image: plugins/docker
    depends_on: [ clone ]
    settings:
      context: packages/docker/nginx-proxy/ddns-sidecar
      dockerfile: packages/docker/nginx-proxy/ddns-sidecar/Dockerfile
      force_tag: true
      password:
        from_secret: DOCKER_PASSWORD
      repo: thrashplay/ddns-sidecar
      tags:
        - latest
        - ${DRONE_BRANCH}
        - ${DRONE_BRANCH}-${DRONE_COMMIT}
      username: thrashplay
    when:
      changeset:
        includes: [ packages/docker/nginx-proxy/ddns-sidecar/** ]

  - name: git-client
    image: plugins/docker
    depends_on: [ clone ]
    settings:
      context: packages/docker/git-client
      dockerfile: packages/docker/git-client/Dockerfile
      force_tag: true
      password:
        from_secret: DOCKER_PASSWORD
      repo: thrashplay/git-client
      tags:
        - latest
        - ${DRONE_BRANCH}
        - ${DRONE_BRANCH}-${DRONE_COMMIT}
      username: thrashplay
    when:
      changeset:
        includes: [ packages/docker/git-client/** ]

  - name: homeassistant
    image: plugins/docker
    depends_on: [ clone ]
    settings:
      context: packages/docker/homeassistant
      dockerfile: packages/docker/homeassistant/Dockerfile
      force_tag: true
      password:
        from_secret: DOCKER_PASSWORD
      repo: thrashplay/homeassistant
      tags:
        - latest
        - ${DRONE_BRANCH}
        - ${DRONE_BRANCH}-${DRONE_COMMIT}
      username: thrashplay
    when:
      changeset:
        includes: [ packages/docker/homeassistant/** ]

  - name: nginx-proxy
    image: plugins/docker
    depends_on: [ clone ]
    settings:
      context: packages/docker/nginx-proxy/nginx-proxy
      dockerfile: packages/docker/nginx-proxy/nginx-proxy/Dockerfile
      force_tag: true
      password:
        from_secret: DOCKER_PASSWORD
      repo: thrashplay/nginx-proxy
      tags:
        - latest
        - ${DRONE_BRANCH}
        - ${DRONE_BRANCH}-${DRONE_COMMIT}
      username: thrashplay
    when:
      changeset:
        includes: [ packages/docker/nginx-proxy/nginx-proxy/** ]

  - name: samba
    image: thrashplay/docker-edit
    depends_on: [ wait-for-docker ]
    environment:
      DOCKER_CERT_PATH: /certs/client
      DOCKER_HOST: tcp://docker:2376
      DOCKER_TLS_VERIFY: true
    settings:
      edit_command: set arch "arm"
      password:
        from_secret: DOCKER_PASSWORD
      source_image: "dperson/samba:armhf"
      # tags:
      #   - latest
      #   - ${DRONE_BRANCH}
      #   - ${DRONE_BRANCH}-${DRONE_COMMIT}
      target_image: "thrashplay/samba-armhf:latest"
      username: thrashplay
    volumes:
      - name: docker-certs
        path: /certs
    when:
      changeset:
        includes: [ packages/drone-plugins/docker-edit/** ]

  - name: service-wrapper
    image: plugins/docker
    depends_on: [ clone ]
    settings:
      context: packages/docker/service-wrapper
      dockerfile: packages/docker/service-wrapper/Dockerfile
      force_tag: true
      password:
        from_secret: DOCKER_PASSWORD
      repo: thrashplay/service-wrapper
      tags:
        - latest
        - ${DRONE_BRANCH}
        - ${DRONE_BRANCH}-${DRONE_COMMIT}
      username: thrashplay
    when:
      changeset:
        includes: [ packages/docker/service-wrapper/** ]
    
trigger:
  changeset:
    includes: [ .drone.yaml, packages/docker/** ]
  branch:
    - master

volumes:
  - name: docker-certs
    temp: {}

---

kind: pipeline
type: docker
name: build-npm-packages

steps:
  - name: initialize
    image: alpine/git
    commands:
      - git config --local user.email drone@thrashplay.com
      - git config --local user.name Drone

  - name: bootstrap
    image: node:lts
    commands:
      - yarn install --frozen-lockfile --non-interactive
      - yarn lerna bootstrap

  - name: build
    image: node:lts
    commands:
      - yarn build

  - name: test
    image: node:lts
    commands:
      - yarn test

  - name: bump-versions
    image: node:lts
    commands:
      - yarn lerna version --conventional-prerelease --preid next --no-changelog --yes
    when:
      branch:
        - master

  - name: authenticate-to-npm
    image: robertstettner/drone-npm-auth
    settings:
      token:
        from_secret: NPM_PUBLISH_TOKEN
    when:
      branch:
        - master

  - name: publish
    image: node:lts
    commands:
      - yarn lerna publish from-package --no-git-reset --dist-tag next --yes
    when:
      branch:
        - master

trigger:
  changeset:
    includes:
      - '.ci/**'
      - '.eslintignore'
      - '.eslintrc.js'
      - '@types/**'
      - 'babel.config.js'
      - 'build-lib/**'
      - 'jest.config.js'
      - 'lerna.json'
      - 'package.json'
      - 'patches/**'
      - 'packages/node/**'
      - 'tsconfig.*.json'
      - 'tsconfig.json'
      - 'yarn.lock'

---

kind: pipeline
type: docker
name: deploy-services

depends_on:
  - build-arm-images
  - build-npm-packages

platform:
  arch: arm
  os: linux

steps:
  - name: generate-versions
    image: thrashplay/generate-versions
    settings:
      stack_files:
        - packages/pegasus-ops/dashboard/docker-compose.yaml
        - packages/pegasus-ops/samba/docker-compose.yaml
        - packages/pegasus-ops/traefik/docker-compose.yaml

  - name: deploy
    image: thrashplay/swarm-management
    settings:
      configuration_file: packages/pegasus-ops/swarm.production.yaml
      docker_host: control.pegasus:2376
      docker_cacert:
        from_secret: DOCKER_CACERT
      docker_cert:
        from_secret: DOCKER_CERT
      docker_key:
        from_secret: DOCKER_KEY
      use_tls: true

trigger:
  branch:
    - master
