kind: pipeline
name: deploy-nginx

steps:
- name: hello
  image: hello-world

trigger:
  changeset:
    includes: [ .drone.yaml, services/sophia/nginx/** ]

# // local deployService(name, path) = {
# //   kind: "pipeline",
# //     name: "deploy-" + name,
# //     steps: [
# //         {
# //             name: hello,
# //             image: "hello-world",
# //         },
# //     ],
# //     trigger: {
# //       changeset: {
# //         includes: [ 
# //           ".drone.jsonnet",
# //           path + "/**"
# //         ],
# //       },
# //     },
# // };

# // [
# //   deployService("nginx", "services/sophia/nginx"),
# // ]