/**
 * This file was auto-generated by swagger-to-ts.
 * Do not make direct changes to the file.
 */

export interface components {
  schemas: {
    /**
     * Error response schema.
     */
    Error: {
      /**
       * Error code indicating the type of failure.
       */
      code: string;
      /**
       * Additional information about the error, if available.
       */
      details?: { [key: string]: any };
      /**
       * HTTP status code associated with the error.
       */
      status: number;
    };
    /**
     * A Git source code repository.
     */
    GitRepository: {
      id: string;
      repositoryType: "git";
      /**
       * URL for this repository.
       */
      url: string;
    };
    SourceCodeRepository: components["schemas"]["GitRepository"];
  };
}
