version: '3.7'
services:
  nginx:
    image: nginx:1.16-alpine
    ports:
      - "8080:8080"
      - "443:443"
    configs:
      - source: nginx_config
        target: /etc/nginx/conf.d/default.conf
        mode: 0440

configs:
  nginx_config:
    name: nginx_config-${SETTINGS_VERSION:-default}
    file: ./config/nginx.conf