version: '3.7'
services:
  nginx:
    image: thrashplay/nginx-with-certbot:latest
    configs:
      - source: proxy-config
        target: /proxy.conf
        mode: 0440
      - source: certificates-config
        target: /etc/nginx/certificates.json
        mode: 0440
    environment:
      - CERTBOT_EMAIL=sean@thrashplay.com
      - CERTBOT_STAGING=true
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - cert-storage:/etc/letsencrypt

  ddns:
    image: thrashplay/ddns-sidecar:latest
    configs:
      - source: ddns-config
        target: /ddns/config.json
        mode: 0440
    environment:
      - CONFIG_SECRETS_FILE=/run/secrets/ddns-secrets
    ports:
      - "8000:8000"
    secrets:
      - ddns-secrets
    volumes:
      - ddns-data:/updater/data

configs:
  ddns-config:
    name: ddns-config-${DDNS_CONFIG_VERSION:-default}
    file: ./config/ddns.json
  proxy-config:
    name: proxy-config-${PROXY_CONFIG_VERSION:-default}
    file: ./config/proxy.conf
  certificates-config:
    name: certificates-config-${CERTIFICATES_CONFIG_VERSION:-default}
    file: ./config/certificates.json

networks:
  default:
    external: true
    name: proxy

secrets:
  ddns-secrets:
    external: true

volumes:
  cert-storage:
    driver: local
    driver_opts:
      type: none
      device: /mnt/nginx-proxy/cert_storage
      o: bind
  ddns-data:
