version: '3.7'
services:
  nginx:
    image: nginx:1.16-alpine
    configs:
      - source: default-config
        target: /etc/nginx/conf.d/default.conf
        mode: 0440
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - cert-storage:/etc/letsencrypt
      - nginx-config:/etc/nginx
      - read_only: true
        source: www-data
        target: /var/www
        type: volume

  certbot:
    image: thrashplay/certbot-nginx:latest
    volumes:
      - cert-storage:/etc/letsencrypt
      - nginx-config:/etc/nginx
      - source: www-data
        target: /var/www
        type: volume

configs:
  default-config:
    name: default-config-${NGINX_CONFIG_VERSION:-default}
    file: ./config/default.conf

volumes:
  cert-storage:
    driver: local
    driver_opts:
      type: none
      device: /mnt/nginx-proxy/cert_storage
      o: bind
  nginx-config:
    driver: local
    driver_opts:
      type: none
      device: /mnt/nginx-proxy/nginx_config
      o: bind
  www-data:
