version: '3.7'

services:
  db:
    image: linuxserver/mariadb:110.4.12mariabionic-ls60
    environment:
      FILE__MYSQL_DATABASE: /run/secrets/guide-on-the-side.mariadb-database
      FILE__MYSQL_PASSWORD: /run/secrets/guide-on-the-side.mariadb-password
      FILE__MYSQL_ROOT_PASSWORD: /run/secrets/guide-on-the-side.mariadb-root-password
      FILE__MYSQL_USER: /run/secrets/guide-on-the-side.mariadb-user
      TZ: America/Chicago
    ports:
      - 3306:3306
    secrets:
      - guide-on-the-side.mariadb-database
      - guide-on-the-side.mariadb-password
      - guide-on-the-side.mariadb-root-password
      - guide-on-the-side.mariadb-user
    volumes:
      - mariadb-data:/config
  web:
    image: "thrashplay/guide-on-the-side"
    configs:
      - source: config.yml.tmpl
        target: /var/www/html/config.yml.tmpl
    deploy:
      labels:
        - "traefik.enable=true"
        # http -> https configuration
        - "traefik.http.routers.guide-on-the-side-http.entrypoints=web"
        - "traefik.http.routers.guide-on-the-side-http.middlewares=https-redirect@file"
        - "traefik.http.routers.guide-on-the-side-http.rule=Host(`gots.the-pegasus.net`)"
        # handle https
        - "traefik.http.routers.guide-on-the-side.entrypoints=websecure"
        - "traefik.http.routers.guide-on-the-side.middlewares=secure@file"
        - "traefik.http.routers.guide-on-the-side.rule=Host(`gots.the-pegasus.net`)"
        - "traefik.http.routers.guide-on-the-side.tls.certresolver=production"
        - "traefik.http.routers.guide-on-the-side.tls.options=default"
        - "traefik.http.services.guide-on-the-side-service.loadbalancer.server.port=80"
    environment:
      - CONFIG_SECRETS_FILE=/run/secrets/guide-on-the-side.credentials
    networks:
      - webgateway
      - default
    secrets:
      - guide-on-the-side.credentials
    volumes:
      - uploads:/var/www/html/app/webroot/uploads

configs:
  config.yml.tmpl:
    name: index-${CONFIG_YML_TMPL:-default}
    file: ./config/config.yml.tmpl

networks:
  default:
    external: true
    name: apptier
  webgateway:
    external: true
    name: webgateway

secrets:
  guide-on-the-side.credentials:
    external: true
  guide-on-the-side.mariadb-database:
    external: true
  guide-on-the-side.mariadb-root-password:
    external: true
  guide-on-the-side.mariadb-user:
    external: true
  guide-on-the-side.mariadb-password:
    external: true

volumes:
  mariadb-data:
    driver: nfs
    name: guide-on-the-side.mariadb-data
    driver_opts:
      create: "true"
      share: nfs.pegasus:/
  uploads:
    driver: nfs
    name: guide-on-the-side.uploads
    driver_opts:
      create: "true"
      share: nfs.pegasus:/
