/* tslint:disable */
/* eslint-disable */
/**
 * Source Control Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    AnyType,
    AnyTypeFromJSON,
    AnyTypeFromJSONTyped,
    AnyTypeToJSON,
} from './';

/**
 * Error response schema.
 * @export
 * @interface ErrorResult
 */
export interface ErrorResult {
    /**
     * Error code indicating the type of failure.
     * @type {string}
     * @memberof ErrorResult
     */
    code: string;
    /**
     * Additional information about the error, if available.
     * @type {AnyType}
     * @memberof ErrorResult
     */
    details?: AnyType;
    /**
     * HTTP status code associated with the error.
     * @type {number}
     * @memberof ErrorResult
     */
    status: number;
}

export function ErrorResultFromJSON(json: any): ErrorResult {
    return ErrorResultFromJSONTyped(json, false);
}

export function ErrorResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): ErrorResult {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'code': json['code'],
        'details': !exists(json, 'details') ? undefined : AnyTypeFromJSON(json['details']),
        'status': json['status'],
    };
}

export function ErrorResultToJSON(value?: ErrorResult | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'code': value.code,
        'details': AnyTypeToJSON(value.details),
        'status': value.status,
    };
}


