version: '3'
services:
  development:
    build: .
    depends_on:
      - android-emulator
    entrypoint: /bin/sh -c "while sleep 1000; do :; done"
    ports:
      - "3000:3000"
      - "8081:8081"
      - "9001:9001"
    volumes:
      - remote-workspace:/workspace
      - /var/run/docker.sock:/var/run/docker.sock

  android-emulator:
    build:
      context: emulator
    privileged: true
    ports:
      - "4723:4723"
      - "5554:5554"
      - "5555:5555"
      - "6080:6080"

  # emulator:
  #   build:
  #     context: emulator
  #     args:
  #       AVD_SYSTEM_IMAGE: "system-images;android-30;google_apis;x86_64"
  #   image: thrashplay/android-emulator-vnc:dev
  #   environment:
  #     AVD_DEVICE: "22"
  #     GROUP_ID: "108"
  #     USER_ID: "997"
  #   devices:
  #   - "/dev/kvm:/dev/kvm"
  #   ports:
  #   - "5901:5901"

volumes:
  remote-workspace: