version: '3'
services:
  development:
    build: .
    entrypoint: /bin/sh -c "while sleep 1000; do :; done"
    volumes:
      - remote-workspace:/workspace
    ports:
    - "8081:8081"

  emulator:
    image: thrashplay/android-emulator-vnc:dev
    environment:
      AVD_DEVICE: "22"
      AVD_SYSTEM_IMAGE: "system-images;android-30;google_apis;x86_64"
      GROUP_ID: "108"
      USER_ID: "997"
    devices:
    - "/dev/kvm:/dev/kvm"
    ports:
    - "5900:5900"

volumes:
  remote-workspace: