version: '3.7'

services:
  ddns:
    image: thrashplay/ddns-sidecar:latest
    configs:
      - source: ddns-config
        target: /ddns/config.json
        mode: 0440
    deploy:
      labels:
        - traefik.enable=true
        - traefik.http.routers.ddns.rule=Host(`ddns.pegasus`)
        - traefik.http.services.ddns-service.loadbalancer.server.port=8000
    environment:
      - CONFIG_SECRETS_FILE=/run/secrets/ddns-secrets
    secrets:
      - ddns-secrets
    volumes:
      - ddns-data:/updater/data

  traefik:
    image: traefik:v2.2
    configs:
      - source: traefik-config
        target: /etc/traefik/traefik.yaml
        mode: 0440
      - source: common-config
        target: /etc/traefik/common-configuration.yaml
        mode: 0440
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.http-catchall.rule=hostregexp(`{host:[a-z-.]+}`)"
        - "traefik.http.routers.http-catchall.entrypoints=web"
        - "traefik.http.routers.http-catchall.middlewares=https-only@file"
      placement:
        constraints:
          - "node.role==manager"
          - "node.labels.public==true"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - certs:/etc/traefik/certs
      - /var/run/docker.sock:/var/run/docker.sock

configs:
  common-config:
    name: traefik-config-${COMMON_CONFIG_VERSION:-default}
    file: ./config/common-configuration.yaml
  ddns-config:
    name: ddns-config-${DDNS_CONFIG_VERSION:-default}
    file: ./config/ddns.json
  traefik-config:
    name: traefik-config-${TRAEFIK_CONFIG_VERSION:-default}
    file: ./config/traefik.yaml

networks:
  default:
    external: true
    name: webgateway

secrets:
  ddns-secrets:
    external: true

volumes:
  ddns-data:
    driver: nfs
    name: traefik.ddns-data
    driver_opts:
      create: "true"
      share: nfs.pegasus:/
  certs:
    driver: nfs
    name: traefik.certs
    driver_opts:
      create: "true"
      share: nfs.pegasus:/