logLevel: "INFO"

api:
  insecure: true

certificatesResolvers:
  production:
    acme:
      email: "sean@thrashplay.com"
      storage: "/etc/traefik/certs/production.json"
      tlsChallenge: {}
  
  # staging:
  #   acme:
  #     caServer: "https://acme-staging-v02.api.letsencrypt.org/directory"
  #     email: "sean@thrashplay.com"
  #     storage: "/etc/traefik/certs/staging.json"
  #     httpChallenge:
  #       entryPoint: web

entryPoints:
  web:
   address: ":80"
  websecure:
    address: ":443"

providers:
  docker:
    exposedByDefault: false
    network: webgateway
    swarmMode: true
  file:
    filename: "/etc/traefik/common-configuration.yaml"

# harden TLS
tls:
  options:
    default:
      cipherSuites:
        - "TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384"
        - "TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384"
        - "TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305"
        - "TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305"
        - "TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256"
        - "TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256"
        # - TLS_ECDHE_ECDSA_AES256_GCM_SHA384
        # - TLS_ECDHE_RSA_AES256_GCM_SHA384
        # - TLS_ECDHE_ECDSA_CHACHA20_POLY1305
        # - TLS_ECDHE_RSA_CHACHA20_POLY1305
        # - TLS_ECDHE_ECDSA_AES128_GCM_SHA256
        # - TLS_ECDHE_RSA_AES128_GCM_SHA256
        # - TLS_ECDHE_ECDSA_AES256_SHA384
        # - TLS_ECDHE_RSA_AES256_SHA384
        # - TLS_ECDHE_ECDSA_AES128_SHA256
        # - TLS_ECDHE_RSA_AES128_SHA256
      minVersion: VersionTLS12